name: Pipline deployment

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ['main']
    types: ['opened', 'synchronize']

jobs:
  avoid_previus:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previus Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm install ci
      - name: Check linter
        run: npm run lint

  deploy:
    needs: ['linter']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm install ci
      - name: Deploy in Vercel
        if: ${{ github.event_name == 'push' }}
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
